version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: ma_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-ma_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ma_pass}
      POSTGRES_DB: ${POSTGRES_DB:-medical_appointment}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:7
    container_name: ma_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@local}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data:
