spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:medical_appointment}
    username: ${POSTGRES_USER:ma_user}
    password: ${POSTGRES_PASSWORD:ma_pass}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

flyway:
  enabled: true

server:
  port: ${SERVER_PORT:8080}
