spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:medical-appointment}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

flyway:
  enabled: true

server:
  port: ${SERVER_PORT:8080}

jwt:
  secret: ${JWT_SECRET:3f2b1c9e7a6d5c4b3a2918076f5e4d3c9b8a7f6e5d4c3b2a1f0e9d8c7b6a5f4}
  expiration-ms: 3600000
