spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:medical_appointment}
    username: ${POSTGRES_USER:ma_user}
    password: ${POSTGRES_PASSWORD:ma_pass}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

flyway:
  enabled: true

server:
  port: ${SERVER_PORT:8080}

jwt:
  secret: ${JWT_SECRET:mudar-em-dev}
  expiration-ms: 3600000 # 1 hora

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha
  show-actuator: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,beans,configprops
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      show-components: always
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true

info:
  app:
    name: Medical Appointment System
    description: Sistema de agendamento médico com Spring Boot
    version: @project.version@
    encoding: @project.build.sourceEncoding@
    java:
      version: @java.version@
  build:
    artifact: @project.artifactId@
    group: @project.groupId@
