spring:
  datasource:
    url: jdbc:h2:mem:ma;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

flyway:
  enabled: false

server:
  port: ${SERVER_PORT:8080}

jwt:
  secret: mudar-em-dev
  expiration-ms: 3600000
